2010/07/01 07:26:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:267
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(242): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(221): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(363): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(86): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(45): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('gii/model')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testdrive\index.php(12): CApplication->run()
#16 {main} REQUEST_URI=/testdrive/index.php?r=gii/model
2010/07/06 09:11:25 [error] [exception.CDbException] exception 'CDbException' with message 'The table "post" for active record class "Post" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:1976
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(342): CActiveRecordMetaData->__construct(Object(Post))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(356): CActiveRecord::model('Post')
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(59): CActiveRecord->getMetaData()
#3 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(39): CActiveRecord->__construct()
#4 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionAdd()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('add')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('post/add')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#11 C:\xampp\htdocs\testdrive\index.php(12): CApplication->run()
#12 {main} REQUEST_URI=/testdrive/index.php?r=post/add
2010/07/06 09:13:10 [error] [exception.CDbException] exception 'CDbException' with message 'The table "post" for active record class "Post" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:1976
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(342): CActiveRecordMetaData->__construct(Object(Post))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(356): CActiveRecord::model('Post')
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(59): CActiveRecord->getMetaData()
#3 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(39): CActiveRecord->__construct()
#4 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionAdd()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('add')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('post/add')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#11 C:\xampp\htdocs\testdrive\index.php(12): CApplication->run()
#12 {main} REQUEST_URI=/testdrive/index.php?r=post/add
2010/07/08 00:11:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "view?id=1".' in C:\xampp\htdocs\yii\framework\web\CController.php:439
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(262): CController->missingAction('view?id=1')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('view?id=1')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('post/view?id=1')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(12): CApplication->run()
#5 {main} REQUEST_URI=/testdrive/index.php?r=post/view?id=1
2010/07/08 00:16:34 [error] [exception.CException] exception 'CException' with message 'Property "Post.link" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(107): CComponent->__get('link')
#1 C:\xampp\htdocs\testdrive\protected\views\post\view.php(9): CActiveRecord->__get('link')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(119): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(748): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(687): CController->renderPartial('view', Array, true)
#6 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(75): CController->render('view', Array)
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionView()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('view')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('post/view')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#14 C:\xampp\htdocs\testdrive\index.php(12): CApplication->run()
#15 {main} REQUEST_URI=/testdrive/index.php?r=post/view&id=1
2010/07/12 01:07:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "latests".' in C:\xampp\htdocs\yii\framework\web\CController.php:439
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(262): CController->missingAction('latests')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('latests')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('post/latests')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(12): CApplication->run()
#5 {main} REQUEST_URI=/testdrive/index.php?r=post/latests
2010/07/12 01:08:50 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT * FROM 'post' 't' WHERE order by dateUpdated desc
in C:\xampp\htdocs\testdrive\protected\controllers\PostController.php (81)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/07/12 01:08:50 [error] [system.db.CDbCommand] Error in querying SQL: SELECT * FROM 'post' 't' WHERE order by dateUpdated desc
in C:\xampp\htdocs\testdrive\protected\controllers\PostController.php (81)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/07/12 01:08:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near "order": syntax error' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:375
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(265): CDbCommand->queryInternal('fetchAll', 2, Array)
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1175): CDbCommand->queryAll()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1310): CActiveRecord->query(Object(CDbCriteria), true)
#3 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(81): CActiveRecord->findAllByAttributes(Array, 'order by dateUp...')
#4 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionLatest()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('latest')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('post/latest')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#11 C:\xampp\htdocs\testdrive\index.php(12): CApplication->run()
#12 {main} REQUEST_URI=/testdrive/index.php?r=post/latest
2010/07/12 01:12:00 [error] [php] include(CDBCriteria.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:338)
Stack trace:
#0 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(81): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionLatest()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(278): PostController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(257): PostController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): PostController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testdrive\index.php(12): CWebApplication->run()
REQUEST_URI=/testdrive/index.php?r=post/latest
in C:\xampp\htdocs\testdrive\protected\controllers\PostController.php (81)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/07/28 09:42:11 [error] [php] Object of class Category could not be converted to string (C:\xampp\htdocs\testdrive\protected\views\post\latest.php:36)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(748): PostController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(687): PostController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(102): PostController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionLatest()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(278): PostController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(257): PostController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): PostController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(12): CWebApplication->run()
REQUEST_URI=/testdrive/index.php?r=post/latest
in C:\xampp\htdocs\testdrive\protected\views\post\latest.php (36)
in C:\xampp\htdocs\testdrive\protected\controllers\PostController.php (102)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/08/02 03:10:54 [error] [php] include(Categoty.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:338)
Stack trace:
#0 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(44): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionAdd()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(278): PostController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(257): PostController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): PostController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testdrive\index.php(12): CWebApplication->run()
REQUEST_URI=/testdrive/index.php?r=post/add
in C:\xampp\htdocs\testdrive\protected\controllers\PostController.php (44)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/08/02 03:12:08 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT * FROM 'category' 't' ORDER BY category desc
in C:\xampp\htdocs\testdrive\protected\controllers\PostController.php (44)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/08/02 03:12:08 [error] [system.db.CDbCommand] Error in querying SQL: SELECT * FROM 'category' 't' ORDER BY category desc
in C:\xampp\htdocs\testdrive\protected\controllers\PostController.php (44)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/08/02 03:12:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: category' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:375
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(265): CDbCommand->queryInternal('fetchAll', 2, Array)
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1175): CDbCommand->queryAll()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1244): CActiveRecord->query(Object(CDbCriteria), true)
#3 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(44): CActiveRecord->findAll(Object(CDbCriteria))
#4 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionAdd()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('add')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('post/add')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#11 C:\xampp\htdocs\testdrive\index.php(12): CApplication->run()
#12 {main} REQUEST_URI=/testdrive/index.php?r=post/add
2010/08/02 03:15:28 [error] [php] Missing argument 2 for CHtml::label(), called in C:\xampp\htdocs\testdrive\protected\views\post\add.php on line 31 and defined (C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php:503)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CBaseController.php(88): PostController->renderInternal()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(748): PostController->renderFile()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(687): PostController->renderPartial()
#3 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(70): PostController->render()
#4 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionAdd()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(278): PostController->runAction()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(257): PostController->runActionWithFilters()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): PostController->run()
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController()
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#11 C:\xampp\htdocs\testdrive\index.php(12): CWebApplication->run()
REQUEST_URI=/testdrive/index.php?r=post/add
in C:\xampp\htdocs\testdrive\protected\views\post\add.php (31)
in C:\xampp\htdocs\testdrive\protected\controllers\PostController.php (70)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/08/02 03:23:39 [error] [php] htmlspecialchars() expects parameter 1 to be string, object given (C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php:66)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(108): renderAttributes()
#1 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(521): tag()
#2 C:\xampp\htdocs\testdrive\protected\views\post\add.php(33): label()
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(119): require()
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(88): PostController->renderInternal()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(748): PostController->renderFile()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(687): PostController->renderPartial()
#7 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(70): PostController->render()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionAdd()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(278): PostController->runAction()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(257): PostController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): PostController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testdrive\index.php(12): CWebApplication->run()
REQUEST_URI=/testdrive/index.php?r=post/add
in C:\xampp\htdocs\testdrive\protected\views\post\add.php (33)
in C:\xampp\htdocs\testdrive\protected\controllers\PostController.php (70)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/08/02 03:24:10 [error] [php] Object of class Category could not be converted to string (C:\xampp\htdocs\testdrive\protected\views\post\add.php:33)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(748): PostController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(687): PostController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(70): PostController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionAdd()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(278): PostController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(257): PostController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): PostController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(12): CWebApplication->run()
REQUEST_URI=/testdrive/index.php?r=post/add
in C:\xampp\htdocs\testdrive\protected\views\post\add.php (33)
in C:\xampp\htdocs\testdrive\protected\controllers\PostController.php (70)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/08/03 08:30:13 [error] [php] Object of class Category could not be converted to string (C:\xampp\htdocs\testdrive\protected\views\post\view.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(748): PostController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(687): PostController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\PostController.php(102): PostController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): PostController->actionView()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(278): PostController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(257): PostController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): PostController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(12): CWebApplication->run()
REQUEST_URI=/testdrive/index.php?r=/post/view&id=15
in C:\xampp\htdocs\testdrive\protected\views\post\view.php (19)
in C:\xampp\htdocs\testdrive\protected\controllers\PostController.php (102)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/09/23 05:49:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "openid".' in C:\xampp\htdocs\yii\framework\web\CController.php:439
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(262): CController->missingAction('openid')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('openid')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('site/openid')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#4 C:\xampp\htdocs\TestDrive\index.php(12): CApplication->run()
#5 {main} REQUEST_URI=/testdrive/index.php?r=site/openid
2010/09/23 05:50:13 [error] [exception.ErrorException] exception 'ErrorException' with message 'Curl extension is required.' in C:\xampp\htdocs\TestDrive\protected\components\EOpenID.php:101
Stack trace:
#0 C:\xampp\htdocs\TestDrive\protected\controllers\SiteController.php(108): EOpenID->__construct()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): SiteController->actionOpenIDLogin()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('OpenIDLogin')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('site/OpenIDLogi...')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#8 C:\xampp\htdocs\TestDrive\index.php(12): CApplication->run()
#9 {main} REQUEST_URI=/testdrive/index.php?r=site/OpenIDLogin
2010/09/23 08:54:16 [error] [php] Object of class EOpenID could not be converted to string (C:\xampp\htdocs\TestDrive\protected\views\site\loggedin.php:4)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(748): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(687): SiteController->renderPartial()
#2 C:\xampp\htdocs\TestDrive\protected\controllers\SiteController.php(118): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): SiteController->actionOpenIDLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(278): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(257): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TestDrive\index.php(12): CWebApplication->run()
REQUEST_URI=/testdrive/index.php?r=site/openIDLogin&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2010-09-23T08%3A53%3A45ZPyAye8KJ0vKzFQ&openid.return_to=http%3A%2F%2Flocalhost%2Ftestdrive%2Findex.php%3Fr%3Dsite%2FopenIDLogin&openid.assoc_handle=AOQobUffXihfTvptft2SxMw9hL6oE9mJK8-8BPbP8338DjCu3ESWYl-P&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=h%2Fg0Qzoltos8jtZWHBm1NrJqa8s%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawnS8m0eUQkoWjpCC-tJg-VlbdkoXysG4-A&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawnS8m0eUQkoWjpCC-tJg-VlbdkoXysG4-A
in C:\xampp\htdocs\TestDrive\protected\views\site\loggedin.php (4)
in C:\xampp\htdocs\TestDrive\protected\controllers\SiteController.php (118)
in C:\xampp\htdocs\TestDrive\index.php (12)
2010/09/23 08:57:11 [error] [php] Object of class EOpenID could not be converted to string (C:\xampp\htdocs\TestDrive\protected\views\site\loggedin.php:4)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(748): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(687): SiteController->renderPartial()
#2 C:\xampp\htdocs\TestDrive\protected\controllers\SiteController.php(118): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): SiteController->actionOpenIDLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(278): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(257): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TestDrive\index.php(12): CWebApplication->run()
REQUEST_URI=/testdrive/index.php?r=site/openIDLogin&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2010-09-23T08%3A53%3A45ZPyAye8KJ0vKzFQ&openid.return_to=http%3A%2F%2Flocalhost%2Ftestdrive%2Findex.php%3Fr%3Dsite%2FopenIDLogin&openid.assoc_handle=AOQobUffXihfTvptft2SxMw9hL6oE9mJK8-8BPbP8338DjCu3ESWYl-P&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=h%2Fg0Qzoltos8jtZWHBm1NrJqa8s%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawnS8m0eUQkoWjpCC-tJg-VlbdkoXysG4-A&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawnS8m0eUQkoWjpCC-tJg-VlbdkoXysG4-A
in C:\xampp\htdocs\TestDrive\protected\views\site\loggedin.php (4)
in C:\xampp\htdocs\TestDrive\protected\controllers\SiteController.php (118)
in C:\xampp\htdocs\TestDrive\index.php (12)
2010/09/28 09:35:44 [error] [exception.ErrorException] exception 'ErrorException' with message 'No identity supplied.' in C:\xampp\htdocs\testdrive\protected\components\EOpenID.php:234
Stack trace:
#0 C:\xampp\htdocs\testdrive\protected\components\EOpenID.php(528): EOpenID->discover()
#1 C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php(116): EOpenID->validate()
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): SiteController->actionOpenIDLogin()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run(Object(CInlineAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters('openIDLogin')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('site/openIDLogi...')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController()
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#9 C:\xampp\htdocs\testdrive\index.php(12): CApplication->run()
#10 {main} REQUEST_URI=/testdrive/index.php?r=site/openIDLogin&openid.mode=cancel&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
2010/10/08 04:31:56 [error] [php] urlencode() expects parameter 1 to be string, object given (C:\xampp\htdocs\yii\framework\web\CUrlManager.php:370)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CUrlManager.php(243): CUrlManager->createUrlDefault()
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(254): CUrlManager->createUrl()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(824): CWebApplication->createUrl()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(881): SiteController->createUrl()
#4 C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php(119): SiteController->redirect()
#5 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): SiteController->actionOpenIDLogin()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(278): SiteController->runAction()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(257): SiteController->runActionWithFilters()
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): SiteController->run()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController()
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#12 C:\xampp\htdocs\testdrive\index.php(12): CWebApplication->run()
REQUEST_URI=/testdrive/index.php?r=site/openIDLogin&openid.assoc_handle=%7BHMAC-SHA1%7D%7B4cae9ebb%7D%7B7rwsVg%3D%3D%7D&openid.claimed_id=http%3A%2F%2Flocalhost%2Fopenid%2Fexamples%2Fserver%2Fserver.php%2Fidpage%3Fuser%3Dstephen&openid.identity=http%3A%2F%2Flocalhost%2Fopenid%2Fexamples%2Fserver%2Fserver.php%2Fidpage%3Fuser%3Dstephen&openid.mode=id_res&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.op_endpoint=http%3A%2F%2Flocalhost%2Fopenid%2Fexamples%2Fserver%2Fserver.php&openid.response_nonce=2010-10-08T04%3A31%3A55ZNULLh8&openid.return_to=http%3A%2F%2Flocalhost%2Ftestdrive%2Findex.php%3Fr%3Dsite%2FopenIDLogin&openid.sig=yV%2Bqm%2FtVL4%2FcgJjRGoJ81zuVWJY%3D&openid.signed=assoc_handle%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cns.sreg%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2Csigned
in C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php (119)
in C:\xampp\htdocs\testdrive\index.php (12)
2010/10/08 14:17:00 [error] [exception.ErrorException] exception 'ErrorException' with message 'Curl extension is required.' in D:\xampplite\htdocs\testdrive\protected\components\EOpenID.php:101
Stack trace:
#0 D:\xampplite\htdocs\testdrive\protected\controllers\SiteController.php(108): EOpenID->__construct()
#1 D:\xampplite\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionOpenIDLogin()
#2 D:\xampplite\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#3 D:\xampplite\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#4 D:\xampplite\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\xampplite\htdocs\yii\framework\web\CWebApplication.php(324): CController->run('openIDLogin')
#6 D:\xampplite\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('site/openIDLogi...')
#7 D:\xampplite\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#8 D:\xampplite\htdocs\testdrive\index.php(12): CApplication->run()
#9 {main} REQUEST_URI=/testdrive/index.php?r=site/openIDLogin
2010/10/08 14:17:00 [error] [exception.ErrorException] exception 'ErrorException' with message 'Curl extension is required.' in D:\xampplite\htdocs\testdrive\protected\components\EOpenID.php:101
Stack trace:
#0 D:\xampplite\htdocs\testdrive\protected\controllers\SiteController.php(108): EOpenID->__construct()
#1 D:\xampplite\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionOpenIDLogin()
#2 D:\xampplite\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#3 D:\xampplite\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#4 D:\xampplite\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\xampplite\htdocs\yii\framework\web\CWebApplication.php(324): CController->run('openIDLogin')
#6 D:\xampplite\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('site/openIDLogi...')
#7 D:\xampplite\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#8 D:\xampplite\htdocs\testdrive\index.php(12): CApplication->run()
#9 {main} REQUEST_URI=/testdrive/index.php?r=site/openIDLogin
2010/10/11 13:37:10 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT * FROM 'userdetails' 't' WHERE openidurl:=openidurl LIMIT 1
in C:\xampp\htdocs\TestDrive\protected\models\Userdetails.php (109)
in C:\xampp\htdocs\TestDrive\protected\controllers\SiteController.php (124)
in C:\xampp\htdocs\TestDrive\index.php (12)
2010/10/11 13:37:10 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 unrecognized token: ":"' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:121
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(174): CDbCommand->prepare()
#1 C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php(410): CDbCommand->bindValue(':openidurl', 'https://www.goo...')
#2 C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php(87): CDbCommandBuilder->bindValues(Object(CDbCommand), Array)
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1174): CDbCommandBuilder->createFindCommand(Object(CDbTableSchema), Object(CDbCriteria))
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1230): CActiveRecord->query(Object(CDbCriteria))
#5 C:\xampp\htdocs\TestDrive\protected\models\Userdetails.php(109): CActiveRecord->find('openidurl:=open...', Array)
#6 C:\xampp\htdocs\TestDrive\protected\controllers\SiteController.php(124): Userdetails->getUserByOpenIdUrl('https://www.goo...')
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): SiteController->actionOpenIDLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('openIDLogin')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('site/openIDLogi...')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#14 C:\xampp\htdocs\TestDrive\index.php(12): CApplication->run()
#15 {main} REQUEST_URI=/testdrive/index.php?r=site/openIDLogin&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2010-10-11T13%3A36%3A38ZNCGi1qTZ3LKx8Q&openid.return_to=http%3A%2F%2Flocalhost%2Ftestdrive%2Findex.php%3Fr%3Dsite%2FopenIDLogin&openid.assoc_handle=AOQobUdiQVa_YPcAw4NgfF-lNS8O7srRNy7UWRPEir_TV-MC8GaMeHvO&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=sk9EEWakPcmQiP2IkUgUd%2BZISUg%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawnS8m0eUQkoWjpCC-tJg-VlbdkoXysG4-A&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawnS8m0eUQkoWjpCC-tJg-VlbdkoXysG4-A
2010/10/11 13:37:36 [error] [exception.CException] exception 'CException' with message 'Property "EOpenID.name" is read only.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\TestDrive\protected\controllers\SiteController.php(125): CComponent->__set('name', 'Stephenlee')
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): SiteController->actionOpenIDLogin()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('openIDLogin')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('site/openIDLogi...')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#8 C:\xampp\htdocs\TestDrive\index.php(12): CApplication->run()
#9 {main} REQUEST_URI=/testdrive/index.php?r=site/openIDLogin&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2010-10-11T13%3A37%3A03Zv8JzBN0bJCkhvw&openid.return_to=http%3A%2F%2Flocalhost%2Ftestdrive%2Findex.php%3Fr%3Dsite%2FopenIDLogin&openid.assoc_handle=AOQobUf2989NdXn4cjt8AANmGva-0GTvw7yNlyENR9hTtGGsTGgYNb28&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=rqjscfZd4uyyXg8HI6FySyK9AV4%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawnS8m0eUQkoWjpCC-tJg-VlbdkoXysG4-A&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawnS8m0eUQkoWjpCC-tJg-VlbdkoXysG4-A
2010/10/11 13:38:21 [error] [exception.CException] exception 'CException' with message 'EOpenID does not have a method named "setName".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:237
Stack trace:
#0 [internal function]: CComponent->__call('setName', Array)
#1 C:\xampp\htdocs\TestDrive\protected\controllers\SiteController.php(125): EOpenID->setName('Stephenlee')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(32): SiteController->actionOpenIDLogin()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(320): CController->run('openIDLogin')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(120): CWebApplication->runController('site/openIDLogi...')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#9 C:\xampp\htdocs\TestDrive\index.php(12): CApplication->run()
#10 {main} REQUEST_URI=/testdrive/index.php?r=site/openIDLogin&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2010-10-11T13%3A37%3A47ZgP1O3TSxoZVfZA&openid.return_to=http%3A%2F%2Flocalhost%2Ftestdrive%2Findex.php%3Fr%3Dsite%2FopenIDLogin&openid.assoc_handle=AOQobUe_qCp_r_tSRdISEYhf_95ZW2BTh_3oSoeK8m3j0f8zbtZ5Nss-&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=ZtF7veBDjGfngyUCPkICk7bvDWs%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawnS8m0eUQkoWjpCC-tJg-VlbdkoXysG4-A&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawnS8m0eUQkoWjpCC-tJg-VlbdkoXysG4-A
